### ISSUE TITLE
[FEATURE] 패키지 구조 설계

### ISSUE THREAD

**Issue by mng990** [mng990/musinsa-test#4]
#### ✨ 기능 설명
---
- 구현 요구 사항과 도메인을 고려해 아키텍쳐를 선정합니다.
- 패키지 구조를 프로젝트에 적용합니다.

#### ✅ TODO
---
- [ ] 무신사 전시개발팀 채용 요구 역량 파악
- [ ] 클린 아키텍쳐, 헥사고날 아키텍쳐 리서치
- [ ] 패키지 구조 확립

#### 📚 참고자료
- [클린 아키텍쳐 예제](https://github.dev/wikibook/clean-architecture/tree/main/src/main)
- [만들면서 배우는 헥사고날 아키텍처 설계와 구현](https://m.yes24.com/Goods/Detail/112927162)
