### ISSUE TITLE
[FEATURE] 과제 1번 API 구현

### ISSUE THREAD

**Issue by mng990** [mng990/musinsa-test#8]
#### ✨ 기능 설명
---
- 무신사 과제 1번 API를 구현합니다.
- 아래 순서대로 API를 구체화 합니다.
1. usecase 
2. 도메인 로직
3. in/out port
4. service
5. in/out adapter (controller, repository)

#### ✅ TODO
---
- [ ] usecase 설계 및 구현
- [ ] 도메인 로직 구현
- [ ] in/out port 구현
- [ ] 서비스 계층 구현
- [ ] in/out adapter 구현

#### 📚 참고자료
---
- 만들면서 배우는 헥사고날 아키텍처 적용과 구현, 다비 비에이라, 2022
- [헥사고날 아키텍처에서 유스케이스 구현하기](https://haon.blog/haon/architecture/hexagonal/usecase/)
- [Harpsharp 프로젝트 Album 도메인](https://github.com/2024KBC10/HarpSharp_SERVER)
